FROM postgres:latest

ENV POSTGRES_DB=django_shop
ENV POSTGRES_USER=cuchi
ENV POSTGRES_PASSWORD=qq

RUN mkdir -p /home/db
RUN cd /home/db
WORKDIR /home/db

COPY sql/ /home/db/
COPY sql/all.sql /docker-entrypoint-initdb.d/

EXPOSE 5432


