# Generated by Django 4.2 on 2023-09-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historialdecompra',
            name='num_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historialdecompra',
            name='package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='minimum_allowed',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.producttag'),
        ),
    ]
