# Generated by Django 4.2.3 on 2023-09-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
