# Generated by Django 4.2.3 on 2023-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo2', '0002_alter_shopproduct_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdecompra',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historialdecompra',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historialdecompra',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historialdeventa',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historialdeventa',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
