# Generated by Django 4.2 on 2023-12-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0003_rename_num_units_historialdecompra_num_units_from_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.AddField(
            model_name='shop',
            name='administrator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
