# Generated by Django 4.2.3 on 2023-09-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo2', '0003_alter_historialdecompra_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdecompra',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
