# Generated by Django 4.2.3 on 2023-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo2', '0004_alter_historialdecompra_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
