version: '3'

services:
  web:
    container_name: shop
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000" 
    depends_on:
      - db

  db:
    container_name: pos_shop
    build:
      context: ../
      dockerfile: docker/Dockerfile-postgres
    environment:
      POSTGRES_DB: django_shop
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
