from .historial_de_compra_serializer import HistorialDeCompraSerializer
from .historial_de_venta_serializer import HistorialDeVentaSerializer
from .product_serializer import ProductSerializer
from .provider_serializer import ProviderSerializer
from .shop_product_serializer import ShopProductSerializer
from .shop_provider_serializer import ShopProviderSerializer
from .shop_serializer import ShopSerializer
from .product_provider_serializer import ProductProviderSerializer