from .product_provider import product_providers_serialized, get_product_provider_serialized
from .products import products_serialized, get_product_serialized
from .providers import providers_serialized, get_provider_serialized
from .shop import shops_serialized, get_shop_serialized
from .historial_compra import historial_de_compras_serialized, get_historial_de_compra_serialized
from .historial_venta import historial_de_ventas_serialized, get_historial_de_venta_serialized